version: '3.0'
services:
  hastebin:
    build: .
    user: "node:node"
    networks:
      - web
    volumes:
      - /home/docker/compose/haste-server/data:/usr/src/app/data
    environment:
      - STORAGE_TYPE=file
      - STORAGE_FILEPATH=/usr/src/app/data
    ports:
      - 7777:7777

networks:
  web:
    external: true
