version: '3.0'
services:
  hastebin:
    build: .
    environment:
      - STORAGE_TYPE=file
      - STORAGE_FILEPATH=/usr/src/app/data
    ports:
      - 7777:7777
  memcached:
    image: memcached:latest
